apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: roboshop # dont forget to mention this.
  #labels in service are used to filter service based on labels . 
  labels:
    component: redis
    project: roboshop
    tier: database
spec:
  clusterIP: None
  selector:
    component: redis
    project: roboshop
    tier: database
  ports:
    - protocol: TCP
      port: 6379 # this is source(service) port
      targetPort: 6379 # container port
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop # dont forget to mention this.
  #labels in service are used to filter service based on labels . 
  labels:
    component: redis
    project: roboshop
    tier: database
spec:
  selector:
    component: redis
    project: roboshop
    tier: database
  ports:
    - protocol: TCP
      port: 6379 # this is source(service) port
      targetPort: 6379 # container port
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace:  roboshop
  labels:
    component: redis
    project: roboshop
    tier: database
spec:
  selector:
    matchLabels:
      component: redis
      project: roboshop
      tier: database # has to match .spec.template.metadata.labels
  serviceName: "redis-headless" # this should be the headless service name because statefulset requires headless service to communicate to pods directly without clusterIp
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        component: redis
        project: roboshop
        tier: database  # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: redis
        image: maha110/redis:v1
        volumeMounts:
        - name: redis-data
          mountPath: /data
      # this is pvc created directly in statfulset resource itself
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 2Gi